name: job-install-and-cache
run-name: Install and cache

on:
  workflow_call:
    inputs:
      path:
        description: The list of dependency path globs to cache
        required: true
        type: string
    outputs:
      cache_hash:
        description: The SHA-256 hash part of the cache key
        value: ${{ jobs.dependencies.outputs.cache_hash }}
      cache_hit:
        description: Whether or not the cache was hit
        value: ${{ jobs.dependencies.outputs.cache_hit }}
      cache_key:
        description: The full cache key used to restore/save the cache
        value: ${{ jobs.dependencies.outputs.cache_key }}

jobs:
  dependencies:
    name: Install and cache
    runs-on: ubuntu-latest

    outputs:
      cache_hit: ${{ steps.cache-hit.outputs.cache_hit }}
      cache_hash: ${{ steps.cache-hash.outputs.cache_hash }}
      cache_key: ${{ steps.cache-key.outputs.cache_key }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          fetch-tags: false

      - name: Set Node.JS 24.x
        uses: actions/setup-node@v6
        with:
          check-latest: true
          node-version: 24.x

      - id: cache-hash
        name: Resolve the SHA-256 hash part of the cache key
        run: |
          echo "cache_hash=${{ hashFiles('package-lock.json') }}" >> ${GITHUB_OUTPUT}

      - id: cache-deps-restore
        name: Restore cached dependencies
        env:
          cache_name: cache-deps
        uses: actions/cache/restore@v4
        with:
          key: ${{ env.cache_name }}-${{ runner.os }}-${{ steps.cache-hash.outputs.cache_hash }}
          path: ${{ inputs.path }}
          restore-keys: |
            ${{ env.cache_name }}-${{ runner.os }}-
            ${{ env.cache_name }}-

      - id: cache-hit
        name: Output cache hit/miss
        run: |
          echo "cache_hit=${{ (steps.cache-deps-restore.outputs.cache-hit == 'true') && 'true' || 'false' }}" >> ${GITHUB_OUTPUT}

      - id: cache-key
        env:
          cache_name: cache-deps
        name: Output cache key
        run: |
          if [[ "${{ steps.cache-hit.outputs.cache_hit }}" == 'true' ]]; then
            echo "cache_key=${{ steps.cache-deps-restore.outputs.cache-matched-key }}" >> ${GITHUB_OUTPUT}
          else
            echo "cache_key=${{ env.cache_name }}-${{ runner.os }}-${{ steps.cache-hash.outputs.cache_hash }}" >> ${GITHUB_OUTPUT}
          fi

      - name: NPM CI
        if: steps.cache-hit.outputs.cache_hit != 'true'
        run: |
          npm ci

      - id: cache-deps-save
        name: Cache dependencies
        env:
          cache_name: cache-deps
        if: always() && steps.cache-hit.outputs.cache_hit != 'true'
        uses: actions/cache/save@v4
        with:
          key: ${{ env.cache_name }}-${{ runner.os }}-${{ steps.cache-hash.outputs.cache_hash }}
          path: ${{ inputs.path }}
