name: job-env
run-name: Environment

on:
  workflow_call:
    outputs:
      branch_name:
        description: |
          The name of the branch this job is running on.
        value: ${{ jobs.resolve-env.outputs.branch_name }}

jobs:
  resolve-env:
    runs-on: ubuntu-latest

    outputs:
      branch_name: ${{ steps.branch-name.outputs.branch_name }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - id: branch-name
        name: Resolve the branch for this workflow run.
        run: |
          if [[ -n "${{ github.event.pull_request.head.ref }}" ]]; then
            echo "branch_name=${{ github.event.pull_request.head.ref }}" >> ${GITHUB_OUTPUT}
          elif [[ -n "${{ github.event.workflow_run.head_branch }}" ]]; then
            echo "branch_name=${{ github.event.workflow_run.head_branch }}" >> ${GITHUB_OUTPUT}
          else
            echo "branch_name=${GITHUB_REF_NAME}" >> ${GITHUB_OUTPUT}
          fi
